// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS9vlVNGBFaD9O0r0VzkYEhi1fNTgJbT0',
    appId: '1:25601981799:web:2a4bb729108983b02103c2',
    messagingSenderId: '25601981799',
    projectId: 'testing-cli-23f53',
    authDomain: 'testing-cli-23f53.firebaseapp.com',
    storageBucket: 'testing-cli-23f53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYbcJMAyDOWTzvoXWOM5LdwmHUqU37_pg',
    appId: '1:25601981799:android:2c606cafaa0a90cc2103c2',
    messagingSenderId: '25601981799',
    projectId: 'testing-cli-23f53',
    storageBucket: 'testing-cli-23f53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmeze_E9tHnr3Kxmqt1I-st8rVu6ptheM',
    appId: '1:25601981799:ios:eb477d67602953662103c2',
    messagingSenderId: '25601981799',
    projectId: 'testing-cli-23f53',
    storageBucket: 'testing-cli-23f53.firebasestorage.app',
    iosBundleId: 'com.ammard3v.ammard3v',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmeze_E9tHnr3Kxmqt1I-st8rVu6ptheM',
    appId: '1:25601981799:ios:eb477d67602953662103c2',
    messagingSenderId: '25601981799',
    projectId: 'testing-cli-23f53',
    storageBucket: 'testing-cli-23f53.firebasestorage.app',
    iosBundleId: 'com.ammard3v.ammard3v',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS9vlVNGBFaD9O0r0VzkYEhi1fNTgJbT0',
    appId: '1:25601981799:web:9d44bb4ed89cb19d2103c2',
    messagingSenderId: '25601981799',
    projectId: 'testing-cli-23f53',
    authDomain: 'testing-cli-23f53.firebaseapp.com',
    storageBucket: 'testing-cli-23f53.firebasestorage.app',
  );
}
